[package]
name = "zoda"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.16.3"

[dependencies]
lalrpop-util = "0.16.3"
regex = "0.2.1"